# Generated by Django 3.0.4 on 2020-06-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0002_auto_20200611_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
