# Generated by Django 3.0.4 on 2020-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0003_auto_20200611_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
