# Generated by Django 3.0.4 on 2020-06-11 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0004_auto_20200611_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
